[phases.setup]
nixPkgs = ["python311"]
aptPkgs = ["libmupdf-dev", "mupdf-tools", "libjpeg-dev", "zlib1g-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"